name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Ruby
      run: |
        sudo apt-get install ruby-full
    - name: Build Project
      run: |
        sudo gem install bundler
        sudo gem install ffi
        sudo bundle install
        sudo cucumber
